version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    environment:
      - DATABASE_URL=postgresql://postgres:passw@db:5432/database
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db


  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passw
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb/import_data.sql:/docker-entrypoint-initdb.d/import_data.sql
      - ./initdb/.data_sanitized2.csv:/.data_sanitized2.csv
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d database"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
